### ISSUE TITLE
Have a global copy of the bashrc in /data/ and then just source it in the user .bashrc file.

### ISSUE THREAD

**Issue by wolfiex** [wacl-york/bashrc_earth0#1]
@kilicomu  Make a .globalbashrc in one of the data folders on earth0. 

Then just add `source <path to .globalbashrc>` or `./<path to .globalbashrc>` in the user bashrc. 

This also does not overwrite the current user bashrc, as is done by the wget -O .bashrc command.

**Comment by kilicomu** [comment]
Cool idea.

I've cloned this repository on earth0 at `/etc/bashrc_earth0`, so you can find the `bashrc` at:

`/etc/bashrc_earth0/bashrc`

I'll update the repository README.md to suggest that this is an option, and send an email to the group.

**Comment by kilicomu** [comment]
I've completed the above tasks, so I'll close the issue.

@wolfiex, feel free to reopen if you don't think it's been resolved.
